
test_that("dependencies", {
  expect_no_error({library(DT)})
  expect_no_error({library(GenomicRanges)})
  expect_no_error({library(MASS)})
  expect_no_error({library(RSQLite)})
  expect_no_error({library(digest)})
  expect_no_error({library(igraph)})
  expect_no_error({library(lubridate)})
  expect_no_error({library(plotly)})
  expect_no_error({suppressWarnings({library(rutilstimflutre)})})
  expect_no_error({library(scrm)})
  expect_no_error({library(shiny)})
  expect_no_error({library(shinycssloaders)})
  expect_no_error({library(shinydashboard)})
  expect_no_error({library(shinyjs)})
  expect_no_error({library(vistime)})
})
